mode: production # Change to "production" before generating a production deployment
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin

publisher:
    default:
        type: hyde.ext.publishers.pyfs.PyFS
        url: "ftp://blanchardjeremy.com:%(password)s@blanchardjeremy.com/domains/blanchardjeremy.com/html/"
urlcleaner:
    index_file_names:
        - index.html
    strip_extensions:
        - html
    append_slash: false
context:
    data:
        site_title: Jeremy Blanchard
        author:
            name: Jeremy Blanchard
            url: "http://blanchardjeremy.com"
        google_analytics_id: UA-1854982-5
        home_url: index.html
        old_date: "June 5th"
        new_date: "June 21st"
        new_date_referrals: "June 21st"

        menu:
            - title: Blog
              url: "http://blog.blanchardjeremy.com"
            - title: Schedule
              url: "/schedule"

        profiles:
            - title: Facebook
              url: "http://www.facebook.com/jeremy.blanchard"
            - title: LinkedIn
              url: "http://www.linkedin.com/in/jeremytblanchard"
            - title: Delicious
              url: "http://delicious.com/auzigog"
            - title: Last.fm
              url: "http://www.last.fm/user/eyeRmonkey"
            - title: Twitter
              url: "http://twitter.com/auzigog"
            - title: Email
              url: "mailto:coach@blanchardjeremy.com"
            - title: GitHub
              url: "http://github.com/auzigog/"
            - title: Flickr
              url: "http://www.flickr.com/photos/eyermonkey/"
            - title: Skype
              url: "skype:auzigog"
